[toolchain]

[features]
resolution = true
skip-lint = true

[programs.devnet]
basic_oracle_example = "3rTiktUXLdYgnsPfPv3YLduUYdLTQANnzC8muZprYYHR"

[programs.mainnet]
basic_oracle_example = "3rTiktUXLdYgnsPfPv3YLduUYdLTQANnzC8muZprYYHR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
crank = "npx ts-node ./scripts/managedUpdate.ts --feedId 0xaf3a39b12f5c052d81eb8c62bb86f4691fce2c2e0c88b39f83801978b6f203c3"
